import { WorkflowSchema } from '../types';

export const CSC_TEMPLATE: WorkflowSchema = {
  workflowId: 'wf_csc_service_app',
  organizationId: 'org_csc_demo',
  name: 'CSC Citizen Service Application',
  description: 'Public e-governance service intake for pensions, certificates, and welfare applications with age calculation and conditional banking logic.',
  version: 1,
  status: 'published',
  collectionModes: ['conversation', 'form', 'operator'],
  publicSlug: 'csc-citizen-service',
  fields: [
    {
      id: 'f_service_type',
      key: 'serviceType',
      label: 'Service Type',
      type: 'single_select',
      required: true,
      description: 'Select the citizen service requested',
      options: [
        'Old Age Pension',
        'Caste Certificate',
        'Income Certificate',
        'Domicile Certificate',
        'Ration Card Update'
      ],
      section: 'Service Selection',
      order: 1,
    },
    {
      id: 'f_applicant_name',
      key: 'applicantName',
      label: 'Applicant Full Name',
      type: 'short_text',
      required: true,
      placeholder: 'e.g. Ramesh Kumar',
      minLength: 3,
      section: 'Personal Details',
      order: 2,
    },
    {
      id: 'f_dob',
      key: 'dob',
      label: 'Date of Birth',
      type: 'date',
      required: true,
      description: 'YYYY-MM-DD format',
      section: 'Personal Details',
      order: 3,
    },
    {
      id: 'f_age',
      key: 'calculatedAge',
      label: 'Calculated Age',
      type: 'calculated',
      required: false,
      description: 'Automatically derived from date of birth',
      derivedFormula: {
        type: 'age_from_dob',
        params: { dobFieldKey: 'dob' },
      },
      section: 'Personal Details',
      order: 4,
    },
    {
      id: 'f_guardian_name',
      key: 'guardianName',
      label: 'Guardian Name',
      type: 'short_text',
      required: true,
      placeholder: 'Parent or Legal Guardian Name',
      description: 'Required if applicant is a minor (under 18)',
      visibleWhen: {
        field: 'calculatedAge',
        operator: 'less_than',
        value: 18,
      },
      section: 'Guardian Information',
      order: 5,
    },
    {
      id: 'f_guardian_rel',
      key: 'guardianRelation',
      label: 'Guardian Relationship',
      type: 'single_select',
      required: true,
      options: ['Father', 'Mother', 'Legal Guardian'],
      visibleWhen: {
        field: 'calculatedAge',
        operator: 'less_than',
        value: 18,
      },
      section: 'Guardian Information',
      order: 6,
    },
    {
      id: 'f_gender',
      key: 'gender',
      label: 'Gender',
      type: 'single_select',
      required: true,
      options: ['Male', 'Female', 'Transgender / Other'],
      section: 'Personal Details',
      order: 7,
    },
    {
      id: 'f_phone',
      key: 'phone',
      label: 'Phone Number',
      type: 'phone',
      required: true,
      placeholder: '10-digit mobile number',
      section: 'Contact Information',
      order: 8,
    },
    {
      id: 'f_email',
      key: 'email',
      label: 'Email Address (Optional)',
      type: 'email',
      required: false,
      placeholder: 'applicant@example.com',
      section: 'Contact Information',
      order: 9,
    },
    {
      id: 'f_address',
      key: 'address',
      label: 'Residential Address',
      type: 'address',
      required: true,
      placeholder: 'House no., Street, Colony / Ward',
      section: 'Address Details',
      order: 10,
    },
    {
      id: 'f_district',
      key: 'district',
      label: 'District',
      type: 'single_select',
      required: true,
      options: ['Jaipur', 'Jodhpur', 'Kota', 'Udaipur', 'Ajmer', 'Bikaner'],
      section: 'Address Details',
      order: 11,
    },
    {
      id: 'f_state',
      key: 'state',
      label: 'State',
      type: 'short_text',
      required: true,
      defaultValue: 'Rajasthan',
      section: 'Address Details',
      order: 12,
    },
    {
      id: 'f_id_type',
      key: 'idType',
      label: 'Identity Document Type',
      type: 'single_select',
      required: true,
      options: ['Aadhaar Card', 'Voter ID Card', 'PAN Card', 'Passport'],
      section: 'Identity Verification',
      order: 13,
    },
    {
      id: 'f_id_number',
      key: 'idNumber',
      label: 'Document Number',
      type: 'short_text',
      required: true,
      placeholder: 'e.g. 12-digit Aadhaar or 10-digit PAN',
      section: 'Identity Verification',
      order: 14,
    },
    {
      id: 'f_bank_holder',
      key: 'bankHolderName',
      label: 'Bank Account Holder Name',
      type: 'short_text',
      required: true,
      description: 'Required for welfare benefit disbursement services',
      visibleWhen: {
        field: 'serviceType',
        operator: 'in',
        value: ['Old Age Pension', 'Income Certificate'],
      },
      section: 'Bank & Direct Benefit Transfer (DBT)',
      order: 15,
    },
    {
      id: 'f_bank_account',
      key: 'bankAccountNumber',
      label: 'Bank Account Number',
      type: 'short_text',
      required: true,
      sensitive: true,
      visibleWhen: {
        field: 'serviceType',
        operator: 'in',
        value: ['Old Age Pension', 'Income Certificate'],
      },
      section: 'Bank & Direct Benefit Transfer (DBT)',
      order: 16,
    },
    {
      id: 'f_bank_ifsc',
      key: 'bankIfsc',
      label: 'Bank IFSC Code',
      type: 'short_text',
      required: true,
      placeholder: 'e.g. SBIN0001234',
      visibleWhen: {
        field: 'serviceType',
        operator: 'in',
        value: ['Old Age Pension', 'Income Certificate'],
      },
      section: 'Bank & Direct Benefit Transfer (DBT)',
      order: 17,
    },
    {
      id: 'f_consent',
      key: 'consent',
      label: 'Citizen Consent & Declaration',
      type: 'boolean',
      required: true,
      description: 'I certify that the information provided is correct to the best of my knowledge.',
      section: 'Declaration',
      order: 18,
    },
    {
      id: 'f_operator_notes',
      key: 'operatorNotes',
      label: 'Operator Verification Notes',
      type: 'long_text',
      required: false,
      placeholder: 'Internal remarks or verified physical documents',
      section: 'Declaration',
      order: 19,
    },
  ],
  createdBy: 'user_csc_admin',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const RESTAURANT_TEMPLATE: WorkflowSchema = {
  workflowId: 'wf_restaurant_order',
  organizationId: 'org_restaurant_demo',
  name: 'Restaurant Food & Dining Order',
  description: 'Digital ordering workflow supporting Dine-in, Takeaway, and Delivery with automated itemized billing, coupons, and tax calculation.',
  version: 1,
  status: 'published',
  collectionModes: ['conversation', 'form', 'operator'],
  publicSlug: 'jaipur-bistro-order',
  fields: [
    {
      id: 'r_order_type',
      key: 'orderType',
      label: 'Order Type',
      type: 'single_select',
      required: true,
      options: ['Dine-in', 'Takeaway', 'Delivery'],
      section: 'Order Mode',
      order: 1,
    },
    {
      id: 'r_table_number',
      key: 'tableNumber',
      label: 'Table Number',
      type: 'number',
      required: true,
      min: 1,
      max: 50,
      description: 'Required for Dine-in orders',
      visibleWhen: {
        field: 'orderType',
        operator: 'equals',
        value: 'Dine-in',
      },
      section: 'Order Mode',
      order: 2,
    },
    {
      id: 'r_delivery_address',
      key: 'deliveryAddress',
      label: 'Delivery Address',
      type: 'address',
      required: true,
      placeholder: 'Street, House No, Landmark, Area',
      visibleWhen: {
        field: 'orderType',
        operator: 'equals',
        value: 'Delivery',
      },
      section: 'Order Mode',
      order: 3,
    },
    {
      id: 'r_customer_name',
      key: 'customerName',
      label: 'Customer Name',
      type: 'short_text',
      required: true,
      placeholder: 'e.g. Ananya Sharma',
      section: 'Customer Contact',
      order: 4,
    },
    {
      id: 'r_customer_phone',
      key: 'customerPhone',
      label: 'Phone Number',
      type: 'phone',
      required: true,
      placeholder: '10-digit mobile number for order status updates',
      section: 'Customer Contact',
      order: 5,
    },
    {
      id: 'r_ordered_items',
      key: 'orderedItems',
      label: 'Food Items',
      type: 'table',
      required: true,
      description: 'Selected items from the menu with quantities',
      section: 'Menu Selection',
      order: 6,
    },
    {
      id: 'r_special_instructions',
      key: 'specialInstructions',
      label: 'Cooking / Preparation Instructions',
      type: 'short_text',
      required: false,
      placeholder: 'e.g. Less spicy, extra napkins, cutlery required',
      section: 'Menu Selection',
      order: 7,
    },
    {
      id: 'r_coupon_code',
      key: 'couponCode',
      label: 'Promo / Coupon Code',
      type: 'short_text',
      required: false,
      placeholder: 'Use WELCOME20 for 20% off',
      section: 'Payment & Billing',
      order: 8,
    },
    {
      id: 'r_subtotal',
      key: 'subtotal',
      label: 'Subtotal (₹)',
      type: 'calculated',
      required: false,
      derivedFormula: {
        type: 'restaurant_totals',
        params: { itemsKey: 'orderedItems', discountCodeKey: 'couponCode', taxRate: 0.05 },
      },
      section: 'Payment & Billing',
      order: 9,
    },
    {
      id: 'r_discount',
      key: 'discount',
      label: 'Discount (₹)',
      type: 'calculated',
      required: false,
      derivedFormula: {
        type: 'restaurant_totals',
        params: { itemsKey: 'orderedItems', discountCodeKey: 'couponCode', taxRate: 0.05 },
      },
      section: 'Payment & Billing',
      order: 10,
    },
    {
      id: 'r_tax',
      key: 'tax',
      label: 'GST / Tax (5%) (₹)',
      type: 'calculated',
      required: false,
      derivedFormula: {
        type: 'restaurant_totals',
        params: { itemsKey: 'orderedItems', discountCodeKey: 'couponCode', taxRate: 0.05 },
      },
      section: 'Payment & Billing',
      order: 11,
    },
    {
      id: 'r_grand_total',
      key: 'grandTotal',
      label: 'Total Payable Amount (₹)',
      type: 'calculated',
      required: false,
      derivedFormula: {
        type: 'restaurant_totals',
        params: { itemsKey: 'orderedItems', discountCodeKey: 'couponCode', taxRate: 0.05 },
      },
      section: 'Payment & Billing',
      order: 12,
    },
    {
      id: 'r_payment_method',
      key: 'paymentMethod',
      label: 'Payment Method',
      type: 'single_select',
      required: true,
      options: ['UPI / QR Code', 'Cash on Delivery / Table', 'Credit / Debit Card'],
      section: 'Payment & Billing',
      order: 13,
    },
  ],
  createdBy: 'user_restaurant_admin',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const RESTAURANT_MENU = [
  { id: 'm1', name: 'Paneer Tikka Pizza (10")', category: 'Pizza', price: 299, desc: 'Fresh cottage cheese, bell peppers, mozzarella' },
  { id: 'm2', name: 'Farmhouse Veg Pizza (10")', category: 'Pizza', price: 279, desc: 'Capsicum, onion, tomato, grilled mushrooms' },
  { id: 'm3', name: 'Cold Coffee with Ice Cream', category: 'Beverages', price: 120, desc: 'Rich brewed espresso blended with vanilla scoop' },
  { id: 'm4', name: 'Virgin Mojito', category: 'Beverages', price: 99, desc: 'Mint, lime, sparkling soda, crushed ice' },
  { id: 'm5', name: 'Peri Peri French Fries', category: 'Sides', price: 140, desc: 'Crispy potato fries dusted with African peri-peri' },
  { id: 'm6', name: 'Garlic Breadsticks with Dip', category: 'Sides', price: 130, desc: 'Baked herb bread with melted cheddar dip' },
  { id: 'm7', name: 'Chocolate Brownie Sundae', category: 'Desserts', price: 160, desc: 'Warm fudge brownie topped with dark chocolate syrup' },
];
